name: Compare
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep "FUNC"
        env: 
          CONTAIN_FUNC : ${{ contains("hello", "ell") }}
          STARTS_WITH_FUNC : $ {{ startsWith("hello", "hel") }}