name: Job Summaries
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "# hello" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
